### ISSUE TITLE
[멘토링] 9/11 김종욱 멘토님 멘토링

### ISSUE THREAD

**Issue by ujkkk** [Co-due/SOMA#109]
## 📝 Description
**무엇을?**
- 멘토링

## ❗️Todo
- [ ] 예외 코드 어떻게 정의할지
- [ ] Exception 어떻게 처리할지
- [ ] 알고리즘 문제 리뷰

## 주의할 점
- [ ] 
- [ ]

**Comment by ujkkk** [comment]
# 9/11 김종욱 멘토님 멘토링

로그인 때  미음미음@ 걸러짐

메세지를 바꾸면 프론트와 강한결합이 나와서.
에러 코드만 내리면, 
모든 에러 상황에 에러 코드
메시지를 내릴 필요 없다.

QA 같이 차트 만들어서 검사할 필요가 있다.

되도록 우리가 내리는 에러 코드를 참고해서 하는게 좋다. HTTP status는 그냥 참고용으로

성공 Response는 메시지로 로그
포스트 때렸을 때 등록된 키를 내려준다. -> 근데 유저 아이디같이 보안에 취약한거는 안내려 주는게 맞

실패에 대한거는 규격이 반드시 있어야한다
성공은

REST API는 한 번 열는 순간 반 평생가기 때문에 확장성이 있는가, 보안적으로 대체할 수 있는가를 잘 고민해야한다. 

status로만 구분 -> 성공에 대한 ID를, 
내부에서 사용하는거면 아이템만 내리거나 전체?를 내리거나]
종합성 체크? 요청에 따라 응답이 다를 

겟 전에 포스트, 등 일 떄 디비 전에 (생성, 업데이트, 삭제) 때 로그 다 찍어야한다.


DB WAS 에서는 모든 로깅
- 컴포넌트 이름 - 그래서 DB 분리

DB서버가 아니어도 로그는 찍어야한다.
- 예외 id 값 찍어서 단계별로 타고타고
- 요청을 보낼 때 무슨 요청을 보낼지도(API Clinet)
- 파일로 저장 기간과 시간
- dev는 2주, 운영은 약 한


이 예외를 봤을 때 retry할 거는 그 예외로 내리는것이 맞고
그렇지 않으면 통째로 처리

실패하면 자체적으로 retry해도되고
retry가 의미 없는 것도 있고

글로벌 핸들러로 처리하면 처리하는 에러를 모두 모야한다

같은 클라이언트 에러라도 retry 가능하고 못할 수 도 있으니깐 
클라이언트

개발자가 다른 로직을 처리할 수 있냐
프론트에서 처리하는게 다르냐 - 로그인 아이디나 비밀번호가

클래스가 다르면 내부를 자세히 안봐도 어떤 에러가 있는지 알 수있으니깐
