### ISSUE TITLE
[Search] 다음 스프린트에 진행 할 예제 코드 찾기

### ISSUE THREAD

**Issue by SongGwanSeok** [Co-due/SOMA#3]
## 📝 Description
**무엇을?**
다음 스프린트 목표 정하기

**왜?**
- 목표 찾기

## ❗️Todo
- [ ] 다양한 커리큘럼 찾아보기
- [ ] 적당한 커리큘럼 정리
- [ ] 적절한 예제 고르기
- [ ] QnA 작성

## ETC
기타사항
