### ISSUE TITLE
[디자인] 그래프 자료구조 구상

### ISSUE THREAD

**Issue by SongGwanSeok** [Co-due/SOMA#37]
## 📝 Description
**무엇을?**
- 그래프 자료구조 구상

**왜?**
- 그래프 자료구조 디자인 구체화

## ❗️Todo
- [ ] 그래프 디자인 아이디어 최대한 많이 내기
- [ ] 시각화에 도움이 되는 그래프 디자인 고르기
- [ ] 여러가지 디자인 피그마로 그리기

## ETC
기타사항
