### ISSUE TITLE
[멘토링] 6/12 김종욱 멘토님 멘토링

### ISSUE THREAD

**Issue by ujkkk** [Co-due/SOMA#6]
## 📝 Description
**무엇을?**
- 김종욱 멘토님과 멘토링

## ❗️Todo
- [ ] 테스트 코드 관련 질문
- [ ] 스프링 프로젝트 구조 잡기
- [ ] Assignee 복수 하는 방법
- [ ] 리뷰어 자동 지정 하는 방법

## ETC
기타사항
